[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && gunicorn config.wsgi --bind 0.0.0.0:$PORT"
healthcheckPath = "/api/health/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
